# Credits

This is heavily influenced or copied from https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  1.4013e-45,  0.0000e+00],
        [ 1.4013e-45,  0.0000e+00,  1.4013e-45],
        [ 0.0000e+00,         nan,         nan],
        [-2.4683e-22,  4.5553e-41,  0.0000e+00]])


Construct a randomly initialized matrix

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6757, 0.3014, 0.1925],
        [0.6119, 0.8748, 0.8575],
        [0.2788, 0.0189, 0.6274],
        [0.3119, 0.9913, 0.5183],
        [0.7432, 0.4257, 0.0095]])


Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


**NOTE** `torch.Size` is in fact a tuple, so it supports the same operations

In [5]:
x[1:3] = 2
print(x)

tensor([[0.6757, 0.3014, 0.1925],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.3119, 0.9913, 0.5183],
        [0.7432, 0.4257, 0.0095]])


# Assignment

1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [40]:
z = torch.rand(2, 17)
print(z)
print(z.size())

tensor([[0.9146, 0.0589, 0.6350, 0.0964, 0.1482, 0.7446, 0.5741, 0.4706, 0.3755,
         0.3497, 0.6388, 0.7210, 0.0261, 0.6043, 0.5120, 0.9013, 0.1685],
        [0.4557, 0.4523, 0.4244, 0.6746, 0.6671, 0.3133, 0.5292, 0.8130, 0.1788,
         0.1631, 0.2499, 0.7417, 0.8894, 0.4251, 0.0718, 0.3692, 0.1777]])
torch.Size([2, 17])


In [41]:
u = torch.rand((3, 1), dtype=torch.float)
print(u)
print(u.size())

tensor([[0.3540],
        [0.9334],
        [0.7359]])
torch.Size([3, 1])


In [43]:
v = torch.ones([5, 2, 1], dtype=torch.long)*7
print(v)
print(v.size())

tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])
torch.Size([5, 2, 1])


In [45]:
w = torch.tensor([0,1,1,1,0], dtype=torch.long)
print(w)
print(w.size())

tensor([0, 1, 1, 1, 0])
torch.Size([5])


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [54]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.3891, 0.6286, 0.6484],
        [2.4820, 2.8667, 2.1638],
        [2.5987, 2.7534, 2.4077],
        [0.4187, 1.3845, 0.9961],
        [1.1145, 1.0070, 0.3995]])


### 2.2 Addition: syntax 2

In [47]:
print(torch.add(x, y))

tensor([[1.5542, 1.0847, 0.7608],
        [2.3145, 2.3584, 2.7850],
        [2.2465, 2.7503, 2.6911],
        [1.1083, 1.4371, 0.6945],
        [0.9136, 0.9063, 0.1809]])


### 2.3 Addition: giving an output tensor

In [48]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.5542, 1.0847, 0.7608],
        [2.3145, 2.3584, 2.7850],
        [2.2465, 2.7503, 2.6911],
        [1.1083, 1.4371, 0.6945],
        [0.9136, 0.9063, 0.1809]])


### 2.4 Addition: in-place

adds `x`to `y`

In [49]:
y.add_(x)
print(y)

tensor([[1.5542, 1.0847, 0.7608],
        [2.3145, 2.3584, 2.7850],
        [2.2465, 2.7503, 2.6911],
        [1.1083, 1.4371, 0.6945],
        [0.9136, 0.9063, 0.1809]])


**NOTE** Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [50]:
print(x[:, 1])

tensor([0.3014, 2.0000, 2.0000, 0.9913, 0.4257])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiply of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [55]:
print(torch.mul(y, x))

tensor([[0.4820, 0.0986, 0.0878],
        [0.9641, 1.7333, 0.3276],
        [1.1974, 1.5068, 0.8153],
        [0.0333, 0.3898, 0.2476],
        [0.2760, 0.2474, 0.0037]])


In [56]:
y.mul_(x)
print(y)

tensor([[0.4820, 0.0986, 0.0878],
        [0.9641, 1.7333, 0.3276],
        [1.1974, 1.5068, 0.8153],
        [0.0333, 0.3898, 0.2476],
        [0.2760, 0.2474, 0.0037]])


In [57]:
print(torch.div(y, x))

tensor([[0.7134, 0.3272, 0.4559],
        [0.4820, 0.8667, 0.1638],
        [0.5987, 0.7534, 0.4077],
        [0.1068, 0.3932, 0.4778],
        [0.3713, 0.5813, 0.3900]])


In [76]:
a = torch.tensor([2, 4])
b = torch.tensor([4, 2])
print(torch.dot(a, b))

tensor(16)


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [77]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [78]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [79]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [80]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [81]:
i = torch.ones(5, 2)
print(i)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [86]:
j = i.numpy()
print(j)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [87]:
torch.from_numpy(j)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [88]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # this is meant as a tensor to be run on the GPU.
    # the .cuda() does this to any parameter it is applied to
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machie.")

CUDA not available on your machie.
